### ISSUE TITLE
Request for an update

### ISSUE THREAD

**Issue by Kallyelish** [KehanGuo2/MolPuzzle#1]
Hello! Thanks again for this amazing work! 
I want to ask if it’s possible to update the Q&A in stage 2 and stage 3. 
It would really help us with our current work. 
Thanks so much in advance!

**Comment by KehanGuo2** [comment]
Hi Kally, thanks for the reminder. The  Q&A in stage 2 and stage 3 are uploaded now. I hope you find this helpful and don't hesitate to contact us with any issues!
